[package]
name = "nacelle"
version = "0.3.1"
edition = "2024"
rust-version.workspace = true
description = "Convenience crate for Nacelle streaming handlers and transport APIs."
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../README.md"
keywords = ["networking", "tokio", "http", "tcp"]
categories = ["asynchronous", "network-programming"]

[features]
default = ["tcp"]
tcp = ["dep:nacelle-tcp"]
buffer-rotation = ["nacelle-tcp?/buffer-rotation"]
error-hints = ["nacelle-core/error-hints"]
experimental-memory = ["nacelle-core/experimental-memory", "nacelle-http?/experimental-memory", "nacelle-tcp?/experimental-memory"]
experimental-openssl-detection = ["tcp", "openssl", "nacelle-tcp/experimental-openssl-detection"]
experimental-thread-per-core = ["dep:core_affinity", "dep:socket2"]
http = ["dep:nacelle-http"]
rustls = ["dep:nacelle-rustls", "nacelle-http?/rustls", "nacelle-tcp?/rustls"]
openssl = ["dep:nacelle-openssl", "nacelle-tcp?/openssl"]
openssl-vendored = ["openssl", "nacelle-openssl/vendored", "nacelle-tcp?/openssl-vendored"]
tls-self-signed = ["rustls", "nacelle-rustls/self-signed", "nacelle-http?/tls-self-signed", "nacelle-tcp?/tls-self-signed"]
phase-timing = ["tcp", "nacelle-tcp/phase-timing"]
bench = []
fuzzing = []

[dependencies]
bytes = { workspace = true }
core_affinity = { workspace = true, optional = true }
nacelle-codec = { workspace = true }
nacelle-core = { workspace = true }
nacelle-http = { workspace = true, optional = true }
nacelle-openssl = { workspace = true, optional = true }
nacelle-rustls = { workspace = true, optional = true }
nacelle-tcp = { workspace = true, optional = true }
socket2 = { workspace = true, optional = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"] }

[package.metadata.docs.rs]
all-features = false
no-default-features = true
features = ["buffer-rotation", "error-hints", "experimental-memory", "experimental-thread-per-core", "http", "phase-timing", "rustls", "tcp", "tls-self-signed"]
